### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Mdahao** [LynnHongLiu/DAH#1]
![image](https://user-images.githubusercontent.com/24453083/129450961-5b807307-2a08-46f5-950a-31e485802e8c.png)

hi sir， Can you tell me how the formula came about?

**Comment by Lyn-L** [comment]
Hi, thanks for pointing out this, and thanks for your interest in our paper. I have double-checked all formulas, and I am sorry for some typos because of our carelessness. The $b_i$ in the second term of Eq.11 should be \hat{y}_i. This formulation is from the classical VI model. The final object function of hash learning contains two parts, the first one is the error between the generative binary codes and the LSH-based labels, and the second one is about the KL divergence. If you have any other questions, please let me know. Thanks.

**Comment by Mdahao** [comment]
> Hi, thanks for pointing out this, and thanks for your interest in our paper. I have double-checked all formulas, and I am sorry for some typos because of our carelessness. The $b_i$ in the second term of Eq.11 should be \hat{y}_i. This formulation is from the classical VI model. The final object function of hash learning contains two parts, the first one is the error between the generative binary codes and the LSH-based labels, and the second one is about the KL divergence. If you have any other questions, please let me know. Thanks.


Thank you very much for your reply. As you said, the first one is the error between the generative binary codes and the Lsh-based labels. However, I look at formula 15, The first part looks like  expectation（Maybe my thinking is wrong.）, which I don't understand.

![image](https://user-images.githubusercontent.com/24453083/129463821-0925059e-8d4e-4ee5-a6c7-1f9bdc24ca81.png)

**Comment by Lyn-L** [comment]
Indeed, the first item in Eq.15 is an expectation. In Eq. 10, the probability is related to the reconstruction error that I have mentioned. Therefore, we finally used such reconstruction loss to approximate the overall expectation since LSH-based codes were closed to mini-batch sampling. 
Due to space limitations, there may be some details that we did not write very clearly. I would like to add an extra file to this Github project to correct some problems and add some details. Thanks for your question. 
BTW, It is very nice to chat with you. Do you want to have another chat sometime? You could send an Email to me.

**Comment by Mdahao** [comment]
> Indeed, the first item in Eq.15 is an expectation. In Eq. 10, the probability is related to the reconstruction error that I have mentioned. Therefore, we finally used such reconstruction loss to approximate the overall expectation since LSH-based codes were closed to mini-batch sampling.
> Due to space limitations, there may be some details that we did not write very clearly. I would like to add an extra file to this Github project to correct some problems and add some details. Thanks for your question.
> BTW, It is very nice to chat with you. Do you want to have another chat sometime? You could send an Email to me.

Of course, it’s my pleasure.
